---
title: "Prepare descriptions"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(jsonlite)
```

# Get the things!

```{r}
# let's try reading them in from github? since they're in another repo

# based on https://github.com/vboyce/multiparty-tangrams/blob/main/code/prep_ms.R

url <- "https://raw.githubusercontent.com/vboyce/multiparty-tangrams/main/"
one_chat <- read_csv(str_c(url, "data/study1/filtered_chat.csv")) |> mutate(rotate = str_c(as.character(numPlayers), "_rotate"))
two_a_chat <- read_csv(str_c(url, "data/study2a/filtered_chat.csv")) |> mutate(rotate = "no_rotate")
two_b_chat <- read_csv(str_c(url, "data/study2b/filtered_chat.csv")) |>
  mutate(rotate = "full_feedback") |>
  select(-`row num`)
two_c_chat <- read_csv(str_c(url, "data/study2c/filtered_chat.csv")) |>
  mutate(rotate = "emoji") |>
  select(-type)
three_chat <- read_csv(str_c(url, "data/study3/filtered_chat.csv")) |>
  inner_join(read_rds(str_c(url, "data/study3/round_results.rds")) |> select(gameId, trialNum, condition = name) |> unique()) |>
  select(-rowid, -type)

combined_chat <- one_chat |>
  rbind(two_a_chat) |>
  rbind(two_b_chat) |>
  rbind(two_c_chat) |>
  mutate(activePlayerCount = NA) |>
  rename(condition = rotate) |>
  rbind(three_chat) |>
  filter(!(is.chitchat)) |>
  mutate(
    text = gsub("\\n", "", fixed = T, spellchecked), # note that this is using spellcorrected version!!!!
    text = gsub("[/?/.]", " ", text),
    text = str_squish(text),
    tangram = gsub("/experiment/tangram_", "", target, fixed = TRUE),
    tangram = gsub(".png", "", tangram, fixed = TRUE)
  ) %>%
  select(gameId, trialNum, repNum, tangram, playerId, role, numPlayers, text, condition)
# so here we instead count non-white space chunks for words

one_round_results <- read_rds(str_c(url, "data/study1/round_results.rds")) %>% mutate(rotate = str_c(as.character(numPlayers), "_rotate"))
two_a_round_results <- read_rds(str_c(url, "data/study2a/round_results.rds")) %>% mutate(rotate = "no_rotate")
two_b_round_results <- read_rds(str_c(url, "data/study2b/round_results.rds")) %>% mutate(rotate = "full_feedback")
two_c_round_results <- read_rds(str_c(url, "data/study2c/round_results.rds")) |> mutate(rotate = "emoji")
three_round_results <- read_rds(str_c(url, "data/study3/round_results.rds")) |> rename(`_id` = "X_id", condition = name)

combined_results <- one_round_results |>
  rbind(two_a_round_results) |>
  rbind(two_b_round_results) |>
  rbind(two_c_round_results) |>
  mutate(activePlayerCount = NA) |>
  rename(condition = rotate) |>
  rbind(three_round_results) |>
  select(realCorrect, gameId, targetNum, repNum, trialNum, condition, numPlayers, activePlayerCount) |>
  unique()

chat <- combined_chat |>
  left_join(combined_results) |>
  write_csv(here("expt_prep_code/combined_chat.csv"))
```

# Prep pilot

Change of plans we're now looking at first and last. 
```{r, eval=F}
first_last <- chat |>
  filter(repNum == 5 | repNum == 0) |>
  filter(!is.na(text)) |>
  filter(condition %in% c("2_rotate", "6_rotate"))



prepped <- first_last |>
  mutate(playerCount = ifelse(is.na(activePlayerCount), numPlayers, activePlayerCount)) |>
  mutate(allCorrect = realCorrect == playerCount - 1) |>
  mutate(size_round = str_c(condition, "_", as.character(repNum + 1))) |>
  select(-numPlayers, -activePlayerCount) #|>
# nest(text=c(role, playerId, text))
```

# Potential censorship

```{r}
# from https://www.cs.cmu.edu/~biglou/resources/bad-words.txt
# but we allow "bigger", "kid", "crime", "crimes", "butt", "laid", "god", "crack" etc
bad <- read_lines(here("expt_prep_code/bad-words-modified.txt")) |> str_c(collapse = "|")

bad_regex <- str_c("\\b(", bad, ")\\b")

is_bad <- function(text) {
  return(str_detect(str_to_lower(text), bad_regex)[1])
}
```


```{r, eval=F}
bad_strings <- prepped |>
  mutate(has_bad = map_lgl(text, is_bad)) |>
  filter(has_bad == T)

# bad_strings |>  View()

nrow(prepped) # 2749
nrow(bad_strings) # 18

prepped |>
  nest(text = c(role, playerId, text)) |>
  nrow() # 787

bad_strings |>
  nest(text = c(role, playerId, text)) |>
  nrow() # 16

# get some of the boobs and fat ones out
# regex isn't perfect since we might be missing plurals but whatever if we anchor only start of word it flags "bit" and "hood" ... sigh
```

```{r, eval=F}
good_strings <- prepped |>
  mutate(has_bad = map_lgl(text, is_bad)) |>
  filter(has_bad == F) |>
  select(-has_bad) |>
  nest(text = c(role, playerId, text))

good_strings |> write_json(here("experiments/expt1/src/test.js"))
```

# Prep expt 2
Here we take the game 3 round 1 and 6 stuff
and again apply light censoring

```{r}
pre_censor <- chat |>
  filter(repNum == 5 | repNum == 0) |>
  filter(!is.na(text)) |>
  filter(condition %in% c("2_thin", "6_thin", "2_thick", "6_thick")) |>
  mutate(playerCount = ifelse(is.na(activePlayerCount), numPlayers, activePlayerCount)) |>
  mutate(allCorrect = realCorrect == playerCount - 1) |>
  mutate(size_round = str_c(condition, "_", as.character(repNum + 1))) |>
  select(-numPlayers, -activePlayerCount)

bad_strings <- pre_censor |>
  mutate(has_bad = map_lgl(text, is_bad)) |>
  filter(has_bad == T)


nrow(pre_censor) # 2749
nrow(bad_strings) # 18

pre_censor |>
  nest(text = c(role, playerId, text)) |>
  nrow() # 787

bad_strings |>
  nest(text = c(role, playerId, text)) |>
  nrow() # 16
```

```{r, eval=F}
good_strings <- pre_censor |>
  mutate(has_bad = map_lgl(text, is_bad)) |>
  filter(has_bad == F) |>
  select(-has_bad) |>
  nest(text = c(role, playerId, text))

good_strings |> write_json(here("experiments/expt1/src/test.js"))
```

# Prep calibration

```{r}
calibration <- read_csv("for_calibration.csv") |>
  select(-utterance) |>
  left_join(chat) |>
  select(-numPlayers, -activePlayerCount)

bad_strings <- calibration |>
  mutate(has_bad = map_lgl(text, is_bad)) |>
  filter(has_bad)

good_strings <- calibration |>
  mutate(has_bad = map_lgl(text, is_bad)) |>
  filter(has_bad == F) |>
  select(-has_bad) #|>
# nest(text = c(role, playerId, text))
write_csv("labelled.csv") #|> #write_json(here("experiments/expt1/src/calibrate.js"))
```

# Choose yoked


```{r}
theme_set(theme_bw())
options <- combined_results |>
  mutate(activePlayers = ifelse(is.na(activePlayerCount), numPlayers, activePlayerCount)) |>
  mutate(correct = ifelse(activePlayers == 1 + realCorrect, 1, 0)) |>
  group_by(gameId, condition, numPlayers) |>
  summarize(correct = sum(correct)) |>
  group_by(condition, numPlayers) |>
  arrange(desc(correct)) |>
  filter(row_number() < 6) |>
  filter(correct > 49)

# choose 5 from each as a starting point

good_games <- options |>
  ungroup() |>
  select(gameId)
```

```{r}
options_2 <- combined_results |>
  inner_join(good_games) |>
  mutate(activePlayers = ifelse(is.na(activePlayerCount), numPlayers, activePlayerCount)) |>
  mutate(pct_correct = realCorrect / (activePlayers - 1)) |>
  group_by(gameId, repNum, condition, numPlayers) |>
  summarize(pct_correct = mean(pct_correct)) |>
  filter(pct_correct > .8 | repNum != 5) |>
  filter(pct_correct > .8 | repNum != 4) |>
  filter(pct_correct > .7) |>
  filter(pct_correct <= 1) |>
  group_by(gameId) |>
  tally() |>
  filter(n == 6)

better_games <- options_2 |>
  ungroup() |>
  select(gameId)


combined_results |>
  inner_join(better_games) |>
  group_by(gameId) |>
  mutate(activePlayers = ifelse(is.na(activePlayerCount), numPlayers, activePlayerCount)) |>
  mutate(pct_correct = realCorrect / (activePlayers - 1)) |>
  group_by(gameId, repNum, condition, numPlayers) |>
  summarize(pct_correct = mean(pct_correct)) |>
  ggplot(aes(x = repNum, y = pct_correct, group = gameId, color = condition)) +
  geom_line()
```

```{r}
bad_word_games <- combined_chat |>
  inner_join(better_games) |>
  mutate(has_bad = map_lgl(text, is_bad)) |>
  filter(has_bad) |>
  select(gameId) |>
  unique()

best_games <- better_games |> anti_join(bad_word_games)
```

```{r}
combined_chat |>
  filter(gameId %in% choose) |>
  mutate(words = str_count(text, "\\S+")) |>
  filter(!is.na(text)) |>
  filter(!is.na(words)) |>
  group_by(gameId, condition, repNum, role) |>
  summarize(words = sum(words)) |>
  filter(gameId %in% choose) |>
  ggplot(aes(x = repNum, y = words, group = gameId, color = condition)) +
  geom_line() +
  facet_wrap(~role)

combined_results |>
  # filter(gameId %in% choose) |>
  inner_join(best_games) |>
  group_by(gameId) |>
  mutate(activePlayers = ifelse(is.na(activePlayerCount), numPlayers, activePlayerCount)) |>
  mutate(pct_correct = realCorrect / (activePlayers - 1)) |>
  group_by(gameId, repNum, condition, numPlayers) |>
  summarize(pct_correct = mean(pct_correct)) |>
  View()
ggplot(aes(x = repNum, y = pct_correct, group = gameId, color = condition)) +
  geom_line()
```

```{r}
choose <- c(
  "Z2WAkYpWiXwuGcdME", "GWCD2NGoiA2n5Wh2i", "zviCQXNM4xWoYTmoY", "MEJ8y7jRW4947MPrH",
  "x8BXJBHh3RxchPoHv", "rSMFkjhskBteiyQMB", "LzNv7CD7gRuxpk7cQ", "MDLyuv29jevaGLSeT",
  "BTbGhXZvjdSFubTBg", "22dyGMRgestp8u5Lc"
)

combined_chat |>
  filter(gameId %in% choose) |>
  mutate(has_bad = map_lgl(text, is_bad)) |>
  filter(!has_bad) |>
  select(-has_bad) |>
  nest(text = c(role, playerId, text)) |>
  write_json(here("experiments/expt1/src/yoked.js"))
```
